import { GoogleGenAI, Type } from "@google/genai";

const getAIClient = () => {
  if (!process.env.API_KEY) {
    throw new Error("API Key not found");
  }
  return new GoogleGenAI({ apiKey: process.env.API_KEY });
};

// Feature 1: Image Editing using Gemini 2.5 Flash Image
export const editImageWithGemini = async (
  base64Image: string,
  promptText: string
): Promise<string> => {
  const ai = getAIClient();
  const model = "gemini-2.5-flash-image";

  try {
    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: "image/jpeg",
              data: base64Image,
            },
          },
          {
            text: promptText,
          },
        ],
      },
    });

    const candidates = response.candidates;
    if (candidates && candidates.length > 0) {
      for (const part of candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
           return part.inlineData.data;
        }
      }
    }
    
    throw new Error("No image generated by Gemini.");
  } catch (error) {
    console.error("Gemini Image Edit Error:", error);
    throw error;
  }
};

// Feature 2: Receipt Extraction (OCR + JSON)
export const extractReceiptData = async (base64Image: string) => {
  const ai = getAIClient();
  const model = "gemini-2.5-flash";

  try {
    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: "image/jpeg",
              data: base64Image,
            },
          },
          {
            text: "Analyze this receipt. Extract the merchant name, total amount, date, and categorize it (Food, Grocery, Travel, Bills, Shopping, Fuel). Return JSON.",
          },
        ],
      },
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            merchant: { type: Type.STRING },
            amount: { type: Type.NUMBER },
            date: { type: Type.STRING, description: "ISO Date string YYYY-MM-DD" },
            category: { type: Type.STRING },
            summary: { type: Type.STRING, description: "Short description of items" }
          },
          required: ["merchant", "amount", "date", "category"]
        }
      }
    });

    try {
       return JSON.parse(response.text || "{}");
    } catch (parseError) {
       console.error("Failed to parse JSON response", parseError);
       throw new Error("Invalid response format from AI");
    }

  } catch (error) {
    console.error("Receipt Extraction Error:", error);
    throw error;
  }
};